### ISSUE TITLE
Plot prediction with intervals

### ISSUE THREAD

**Issue by andreykirson** [stanfordmlgroup/ngboost#103]
Does it include function to plot the prediction with prediction intervals?

**Comment by alejandroschuler** [comment]
No, it's not really feasible to plot when the number of predictors is greater than two. Also, the construction of the prediction interval depends on the chosen distribution. Right now that's left to the user to do based on the predicted distributional parameters, but we could add methods to each distribution that return x% prediction intervals if that's something many users are interested in.

**Comment by andreykirson** [comment]
Would you mind give a link how to get prediction interval according to chosen distribution.

**Comment by tonyduan** [comment]
@andreykirson Not sure if this is exactly what you're looking for, but here's the code we used to plot the 95% prediction interval in Fig 1 of our paper: [[Code]](https://github.com/stanfordmlgroup/ngboost/blob/26787178d958d3801572391a84f202d545aaecd9/figures/toy_single.py#L62).

In this case the outcome is modeled as a Normal distribution so the 95% interval is just μ ± 1.96 σ. More generally you can use `preds.ppf(quantile)` or the like which calls the corresponding `scipy` function.

**Comment by tonyduan** [comment]
Closing this for now, feel free to re-open if necessary.
