### ISSUE TITLE
Error saving model

### ISSUE THREAD

**Issue by joseramoncajide** [stanfordmlgroup/ngboost#104]
Hi!
First of all, congratulations for your excellent work.
I'm trying to save the model using `pickle.dump`  command. Every thing works as in the documentation but when the model  is fitted using an exponential distribution it fails:

```
foo = NGBRegressor(Dist=Exponential).fit(X_train, Y_train)

pkl_filename = os.path.join('/content/drive/My Drive/models', 'best_ngb_model.p')
with open(pkl_filename, 'wb') as file:
    pickle.dump(foo, file)
```
Error msg:
`AttributeError: Can't pickle local object 'NGBRegressor.__init__.<locals>.DistWithUncensoredScore'`

If using:

```
import joblib
joblib.dump(foo, "foo.joblib.dat")
```

The error details are:

`PicklingError: Can't pickle <class 'ngboost.api.NGBRegressor.__init__.<locals>.DistWithUncensoredScore'>: it's not found as ngboost.api.NGBRegressor.__init__.<locals>.DistWithUncensoredScore`

Any idea?

**Comment by ethansyh** [comment]
Same here, we found out once the Dist=LogNormal or Exponential during training, the model cannot be saved.

**Comment by alejandroschuler** [comment]
Interesting! I'll look into it today, I'm pretty sure it should be an easy fix.

**Comment by alejandroschuler** [comment]
Should be fixed now https://github.com/stanfordmlgroup/ngboost/commit/38a152fa1c9e1ae7385f99d80c74e400706eb5f8 

Let me know if you have any problems!

**Comment by joseramoncajide** [comment]
Now it works! 
Thanks @alejandroschuler
