### ISSUE TITLE
Feature importances raises error

### ISSUE THREAD

**Issue by jirvin16** [stanfordmlgroup/ngboost#112]
I think this condition:
https://github.com/stanfordmlgroup/ngboost/blob/master/ngboost/ngboost.py#L381

can cause the code to break due to different numbers of values in the weighted average:

https://github.com/stanfordmlgroup/ngboost/blob/master/ngboost/ngboost.py#L393-L395

Deleting that line fixed the error for me, but not sure if that's the correct way to fix.

**Comment by alejandroschuler** [comment]
Yep, you're definitely right about that condition causing problems. It seems like deleting that line is a safe fix, but I'm hesitant because I'm not sure what the purpose of it is in the first place. @zhiruiwang - could you clarify?

**Comment by zhiruiwang** [comment]
@alejandroschuler That condition is for checking whether the model has been fitted. If the model has not been fitted, the self.base_models will be an empty list and we do not want to proceed forward.

**Comment by alejandroschuler** [comment]
Oh, sorry @zhiruiwang I made a push earlier that changed the line numbers and the links above. We're actually talking about what is now line [393](https://github.com/stanfordmlgroup/ngboost/blob/2ae82bd7b05fa463547adc97551849ade5a980d5/ngboost/ngboost.py#L393), not 381.

**Comment by zhiruiwang** [comment]
@alejandroschuler I am following the same way sklearn create feature importance for RandomForestClassifier: https://github.com/scikit-learn/scikit-learn/blob/95d4f0841/sklearn/ensemble/_forest.py#L432

**Comment by alejandroschuler** [comment]
Oh, got it. In that case, I think we can get rid of that condition, although I don't think it's something we would ever run into in the first place. Thanks! 

https://github.com/stanfordmlgroup/ngboost/commit/c981c153c04b3d3028559c59d2be55d355467bee
