### ISSUE TITLE
Sample weighting with minibatch_frac != 1 breaks

### ISSUE THREAD

**Issue by macklin-fluehr** [stanfordmlgroup/ngboost#114]
Given the current implementation of sample weighting, you cannot batch. Code runs with minibatch_frac=1. but any other value will break. 

It looks like the size of sample_weight right now is fixed (see line 202 of ngboost/ngboost.py), despite the fact that sample sizes will change with different batch sizes. 

The first error I get is a numpy error, which points me towards the differing array sizes:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-401-d3c01d0cd6b6> in <module>
      7 
      8 ngb.fit(X_train, y_train, X_val=X_test, Y_val=y_test, early_stopping_rounds=3, 
----> 9         sample_weight=w_train, val_sample_weight=w_test)

~/miniconda3/envs/pricing_regressor/lib/python3.7/site-packages/ngboost/ngboost.py in fit(self, X, Y, X_val, Y_val, sample_weight, val_sample_weight, train_loss_monitor, val_loss_monitor, early_stopping_rounds)
    216             D = self.Manifold(P_batch.T)
    217 
--> 218             loss_list += [train_loss_monitor(D, Y_batch)]
    219             loss = loss_list[-1]
    220             grads = D.grad(Y_batch, natural=self.natural_gradient)

~/miniconda3/envs/pricing_regressor/lib/python3.7/site-packages/ngboost/ngboost.py in <lambda>(D, Y)
    202         if not train_loss_monitor:
    203             train_loss_monitor = lambda D, Y: D.total_score(
--> 204                 Y, sample_weight=sample_weight
    205             )
    206 

~/miniconda3/envs/pricing_regressor/lib/python3.7/site-packages/ngboost/scores.py in total_score(self, Y, sample_weight)
      5 class Score:
      6     def total_score(self, Y, sample_weight=None):
----> 7         return np.average(self.score(Y), weights=sample_weight)
      8 
      9     def grad(self, Y, natural=True):

<__array_function__ internals> in average(*args, **kwargs)

~/miniconda3/envs/pricing_regressor/lib/python3.7/site-packages/numpy/lib/function_base.py in average(a, axis, weights, returned)
    405             if axis is None:
    406                 raise TypeError(
--> 407                     "Axis must be specified when shapes of a and weights "
    408                     "differ.")
    409             if wgt.ndim != 1:

TypeError: Axis must be specified when shapes of a and weights differ.

**Comment by alejandroschuler** [comment]
I think I've fixed this with https://github.com/stanfordmlgroup/ngboost/commit/2ae82bd7b05fa463547adc97551849ade5a980d5. A working example is now provided [here](https://stanfordmlgroup.github.io/ngboost/1-useage.html#Other-Arguments).

Thanks for catching this! Will close for now, but please comment and reopen if you still have this problem after updating.
