### ISSUE TITLE
I can't save Models.

### ISSUE THREAD

**Issue by RosaShao** [stanfordmlgroup/ngboost#115]
When I use the save way given in 'NGBoost User Guide'.

`import pickle
from pathlib import Path

file_path = Path.home()/'Desktop'/'ngbtest.p'

with file_path.open("wb") as f:
    pickle.dump(ngb, f)`

I got that:

Can't pickle local object 'manifold.<locals>.Manifold'

I can save other models in the same way but NGBoost not.
Is anything wrong? Can you help me? Thank you very much!

By the way, I use python 3.5.

**Comment by alejandroschuler** [comment]
@RosaShao please install the latest version of the package. This was an issue that existed with previous versions of the code and has since been resolved. I'm going to close the issue for now but let me know if updating doesn't solve the problem.
