### ISSUE TITLE
Class Weights

### ISSUE THREAD

**Issue by mustfkeskin** [stanfordmlgroup/ngboost#117]
How i can assign class weights for imbalanced classification problem

**Comment by aoelvp94** [comment]
I have the same problem

**Comment by alejandroschuler** [comment]
Construct the weights manually (e.g. `weights = y*w1 + (1-y)*w0` where `w1` and `w0` are the weights for classes 1 and 0, respectively) and then use the `[sample_weight](https://stanfordmlgroup.github.io/ngboost/1-useage.html#Other-Arguments)` argument.
