### ISSUE TITLE
syntax error in the user guide for early stopping

### ISSUE THREAD

**Issue by rehan814** [stanfordmlgroup/ngboost#118]
There is a typo in the user guide under the heading early stopping. 
It states that early stopping is a parameter to the NGBRegressor whereas its a parameter
for the fit function. 

Current 
_ = NGBRegressor(early_stopping_rounds=2).fit(X_reg_train, Y_reg_train, X_val=X_reg_test, Y_val=Y_reg_test) 

Proposed:
_ = NGBRegressor().fit(X_reg_train, Y_reg_train, X_val=X_reg_test, Y_val=Y_reg_test, early_stopping_rounds=2)

**Comment by tonyduan** [comment]
Thanks for pointing this out, should be fixed in [[this commit]](https://github.com/stanfordmlgroup/ngboost/commit/e3c78d43a62795b0c94c76043c554d7fe587bc64).
