### ISSUE TITLE
Beta Bernoulli distribution

### ISSUE THREAD

**Issue by guyko81** [stanfordmlgroup/ngboost#123]
I have tried to implement Beta Bernoulli but I can't seem to solve the problem The np.linalg.solve failed with singular matrix error. When I tried to solve with np.linalg.lstsq it basically never learnt after the first iteration. 
I would be very happy if someone could help, I hope my differentiation wrt log(alpha) and log(beta) was correct.
There's an add-on package, as beta-binomial in scipy has no fit function.

Please check my version, I don't create pull request until it works. I tried to add Beta and Beta Bernoulli as well, never tried Beta on real (0,1) data yet.
https://github.com/guyko81/ngboost/tree/beta-distribution

**Comment by tonyduan** [comment]
Hi -- to make this easier to review would you mind making a PR?

**Comment by guyko81** [comment]
Created [#124 Beta distribution](https://github.com/stanfordmlgroup/ngboost/pull/124)
