### ISSUE TITLE
Releases to PyPI and conda-forge

### ISSUE THREAD

**Issue by ericmjl** [stanfordmlgroup/ngboost#13]
Hello! I am very excited to see this package :tada:. Was wondering what the release plan to PyPI and conda-forge is? If you make a PyPI package, I am happy to help build the conda-forge recipe for you.

**Comment by avati** [comment]
Hi @ericmjl, that would be awesome, thanks so much! We do have a PyPI version ( at https://pypi.org/project/ngboost/) but that is from an older snapshot. We are yet to make a release with the later code (currently git HEAD is better than the previous PyPI release). Having a conda-forge would be awesome!

[offtopic] your BNN video was one of my first introductions to the topic and it was very helpful back then, thank you!!

**Comment by ericmjl** [comment]
> [offtopic] your BNN video was one of my first introductions to the topic and it was very helpful back then, thank you!!

Oh wow, that's super nice to hear :smile: Totally made my day. I'm saving this in my #feelgood folder :tada:

I will go ahead and submit a build to conda-forge. Maintenance is super easy, there's a bot that the conda-forge developers built that keeps conda-forge in-sync with the PyPI releases, so you only have to worry about:

1. Making PyPI releases, and
2. Approving and merging PRs to the conda-forge recipe repository.

I do this for a few packages that I've been keeping tabs on, (hypothesis, and a few others) and those package maintainers also help with step 2 when I go offline for a few days.

**Comment by avati** [comment]
That sounds good and do-able, thanks @ericmjl!

**Comment by ericmjl** [comment]
OK, conda-forge package is available! Now, every time you all make a PyPI release, a conda-forge bot will update the conda-forge recipe. Looking forward to using this package!

**Comment by avati** [comment]
Is this issue good for closing for now @ericmjl ?

**Comment by ericmjl** [comment]
Yes indeed!
