### ISSUE TITLE
some benchmark with xgboost/lightgbm

### ISSUE THREAD

**Issue by stanpcf** [stanfordmlgroup/ngboost#130]
Hi, many thx for great work for boosting. 
If it's better for ngboost, which have benchmark with other gbdts, such as xgboost/lightgbm. Such as [lightgbm experiments](https://lightgbm.readthedocs.io/en/latest/Experiments.html)

**Comment by alejandroschuler** [comment]
Hi @stanpcf- some results of this kind can be found in [our paper](https://arxiv.org/abs/1910.03225).

However, I want to emphasize that ngboost is *not* a direct competitor with xgboost, lightgbm, etc. Those methods focus on standard (point) prediction, whereas ngboost is for *probabilistic* prediction. Ngboost can still be used for point prediction, but if point prediction is your only goal, other boosting methods are practically guaranteed to be faster and (slightly) better performing. 

I'm going to close this for now, but if you want to see or propose any specific experiments please feel free to comment. Or, better yet, do those experiments and write them up! :) Happy to provide feedback.
