### ISSUE TITLE
Reproducing the plots in the paper

### ISSUE THREAD

**Issue by hiyamgh** [stanfordmlgroup/ngboost#136]
Hello,

I cannot find the code that could help us reproduce the plots in the NGBoost paper, could you please add it ?

**Comment by tonyduan** [comment]
You can find the relevant code in the [[figures/]](https://github.com/stanfordmlgroup/ngboost/tree/master/figures) directory.

I just pushed an update that ensures it's compatible with some of our recent API changes.
