### ISSUE TITLE
NLL by MC dropout in comparison to NGBoost's NLL

### ISSUE THREAD

**Issue by hiyamgh** [stanfordmlgroup/ngboost#141]
Hello,

I am trying to reproduce similar experiments to the one conducted by NGBoost's paper, whereby I want to compare the results by NGBoost to those by MC Dropout, Deep Ensembles, etc.

I know very well the formula used for computing negative log likelihood for NGBoost is as follows:
```
# the final prediction for this fold with the best_itr parameter
        forecast = ngb.pred_dist(X_test, max_iter=best_itr)
        forecast_val = ngb.pred_dist(X_val, max_iter=best_itr)

        # set the appropriate scale if using a homoskedastic Normal
        if args.distn == "NormalFixedVar":
            scale = (
                forecast.var * ((forecast_val.loc - y_val.flatten()) ** 2).mean() ** 0.5
            )
            forecast = norm_dist(loc=forecast.loc, scale=scale)

        ngb_rmse += [np.sqrt(mean_squared_error(forecast.mean(), y_test))]
        ngb_nll += [-forecast.logpdf(y_test.flatten()).mean()]
```

However, the ```log likelihood``` defined by [MC dropout paper](https://arxiv.org/pdf/1506.02142.pdf) is as follows:

![Screenshot (662)](https://user-images.githubusercontent.com/35295550/86007401-01321280-ba20-11ea-9420-bc8df0552002.png)

Should we use this as is ? Or should we modify it in some way ?

**Comment by astrogilda** [comment]
If I understand correctly, MC dropout is used to obtain epistemic
uncertainty, while NGBoost outputs aleatoric unc. So the two can't be
directly compared.

**Comment by hiyamgh** [comment]
@astrogilda  do you know then how can we compare NGB NLL to MC Dropout NLL ? Similarly Concrete Droput ?

**Comment by astrogilda** [comment]
Unfortunately I don't. AFAIK Concrete Dropout is also a way to bootstrap
(just like MC Dropout), and hence calculates a diff. type of uncertainty
than NGB. Let's wait to hear from one of the developers.

**Comment by hiyamgh** [comment]
@tonyduan could you please help. Thank you so much in advance.

**Comment by tonyduan** [comment]
NGBoost attempts to predict aleatoric uncertainty i.e. the variance in p(y|x;θ) through regression from covariates x. MC dropout attempts to predict epistemic uncertainty i.e. uncertainty in the parameters θ through Monte Carlo samples. 

So you wouldn't expect them to obtain predictive uncertainty in the same way. Use the NGBoost code to calculate log-likelihood of data under predictions from NGBoost, and use the MC dropout equation to calculate log-likelihood of data under predictions from MC dropout.
