### ISSUE TITLE
beta distribution 

### ISSUE THREAD

**Issue by astrogilda** [stanfordmlgroup/ngboost#144]
Hey! Is there any plan to introduce beta distribution with ngboost? For a problem I am dealing with, the single output variable of interest is clearly beta-distributed, and so far I've been using power transform from sklearn to convert it into gaussian, but I was wondering if there was a way to bypass this and natively deal with such a variable.

**Comment by alejandroschuler** [comment]
At this point, ngboost is fully "in the wild" and we have no plans to develop any particular features as far as I know. Adding new distributions, however, is something that we encourage the community to do and we provide [specific support](https://stanfordmlgroup.github.io/ngboost/5-dev.html) for that in the user guide (of course anyone is welcome to develop other kinds of features too, but they would have to familiarize themselves with the codebase first). There are two pending PRs (#143 #132) that add new distributions- please feel free to join those by contributing a beta distribution!

**Comment by astrogilda** [comment]
Understood!
