### ISSUE TITLE
Import error for NGBoost

### ISSUE THREAD

**Issue by Sattyi** [stanfordmlgroup/ngboost#145]
While importing NGBoost, getting below error.

`**from ngboost import NGBRegressor**`

Traceback (most recent call last):

  File "/home/satish_agarwal/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-92fcbd405ac3>", line 1, in <module>
    from ngboost import NGBRegressor

**Comment by alejandroschuler** [comment]
This doesn't list what the error was.

**Comment by alejandroschuler** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Sattyi** [comment]
Hi,
I understood MRE...below is the details:

### **Ran the below code:**

```
pip install --upgrade git+https://github.com/stanfordmlgroup/ngboost.git
from ngboost import NGBRegressor
```


After running the code, getting the below system generated message and error.

Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/stanfordmlgroup/ngboost.git
  Cloning https://github.com/stanfordmlgroup/ngboost.git to /tmp/pip-req-build-g788_72r
  Running command git clone -q https://github.com/stanfordmlgroup/ngboost.git /tmp/pip-req-build-g788_72r
Requirement already satisfied, skipping upgrade: numpy>=1.17.2 in ./.local/lib/python3.5/site-packages (from ngboost==0.2.1.dev0) (1.18.3)
Requirement already satisfied, skipping upgrade: scipy>=1.3.1 in ./.local/lib/python3.5/site-packages (from ngboost==0.2.1.dev0) (1.4.1)
Requirement already satisfied, skipping upgrade: scikit-learn>=0.21.3 in ./.local/lib/python3.5/site-packages (from ngboost==0.2.1.dev0) (0.22.2.post1)
Requirement already satisfied, skipping upgrade: tqdm>=4.36.1 in ./.local/lib/python3.5/site-packages (from ngboost==0.2.1.dev0) (4.45.0)
Requirement already satisfied, skipping upgrade: lifelines>=0.22.8 in ./.local/lib/python3.5/site-packages (from ngboost==0.2.1.dev0) (0.23.9)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in ./.local/lib/python3.5/site-packages (from scikit-learn>=0.21.3->ngboost==0.2.1.dev0) (0.14.1)
Requirement already satisfied, skipping upgrade: autograd>=1.3 in ./.local/lib/python3.5/site-packages (from lifelines>=0.22.8->ngboost==0.2.1.dev0) (1.3)
Requirement already satisfied, skipping upgrade: matplotlib>=3.0 in ./.local/lib/python3.5/site-packages (from lifelines>=0.22.8->ngboost==0.2.1.dev0) (3.0.3)
Requirement already satisfied, skipping upgrade: pandas>=0.23.0 in ./.local/lib/python3.5/site-packages (from lifelines>=0.22.8->ngboost==0.2.1.dev0) (0.25.3)
Requirement already satisfied, skipping upgrade: autograd-gamma>=0.3 in ./.local/lib/python3.5/site-packages (from lifelines>=0.22.8->ngboost==0.2.1.dev0) (0.4.2)
Requirement already satisfied, skipping upgrade: future>=0.15.2 in ./.local/lib/python3.5/site-packages (from autograd>=1.3->lifelines>=0.22.8->ngboost==0.2.1.dev0) (0.18.2)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in ./.local/lib/python3.5/site-packages (from matplotlib>=3.0->lifelines>=0.22.8->ngboost==0.2.1.dev0) (2.8.1)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in ./.local/lib/python3.5/site-packages (from matplotlib>=3.0->lifelines>=0.22.8->ngboost==0.2.1.dev0) (0.10.0)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./.local/lib/python3.5/site-packages (from matplotlib>=3.0->lifelines>=0.22.8->ngboost==0.2.1.dev0) (2.4.7)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in ./.local/lib/python3.5/site-packages (from matplotlib>=3.0->lifelines>=0.22.8->ngboost==0.2.1.dev0) (1.1.0)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in ./.local/lib/python3.5/site-packages (from pandas>=0.23.0->lifelines>=0.22.8->ngboost==0.2.1.dev0) (2019.3)
Requirement already satisfied, skipping upgrade: six>=1.5 in ./.local/lib/python3.5/site-packages (from python-dateutil>=2.1->matplotlib>=3.0->lifelines>=0.22.8->ngboost==0.2.1.dev0) (1.14.0)
Requirement already satisfied, skipping upgrade: setuptools in ./.local/lib/python3.5/site-packages (from kiwisolver>=1.0.1->matplotlib>=3.0->lifelines>=0.22.8->ngboost==0.2.1.dev0) (46.1.3)
Building wheels for collected packages: ngboost
  Building wheel for ngboost (setup.py) ... done
  Created wheel for ngboost: filename=ngboost-0.2.1.dev0-py3-none-any.whl size=32644 sha256=cd4ea7bdfe5daddee7eb968d58b9ba934005644948890afc734f574bab71c1ca
  Stored in directory: /tmp/pip-ephem-wheel-cache-3rc4w610/wheels/21/1d/db/505d245619eeae045bec186d483f83b7bb5959029c7fa9b0f4
Successfully built ngboost
Installing collected packages: ngboost
  Attempting uninstall: ngboost
    Found existing installation: ngboost 0.2.1.dev0
    Uninstalling ngboost-0.2.1.dev0:
      Successfully uninstalled ngboost-0.2.1.dev0
Successfully installed ngboost-0.2.1.dev0
Note: you may need to restart the kernel to use updated packages.



Traceback (most recent call last):

  File "/home/satish_agarwal/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-92fcbd405ac3>", line 1, in <module>
    from ngboost import NGBRegressor

  File "/home/satish_agarwal/.local/lib/python3.5/site-packages/ngboost/__init__.py", line 1, in <module>
    from .ngboost import NGBoost

  File "/home/satish_agarwal/.local/lib/python3.5/site-packages/ngboost/ngboost.py", line 267
    print(f"== Early stopping achieved.")
                                       ^
SyntaxError: invalid syntax

**Comment by tonyduan** [comment]
Can you confirm what version of Python you're running? We require 3.6+.

**Comment by Sattyi** [comment]
It's Python 3.5.3.
Can I run on Python 3.7?

**Comment by Sattyi** [comment]
Yes, error not coming in Python 3.7. Thanks!
