### ISSUE TITLE
Combining bagging with ngboost

### ISSUE THREAD

**Issue by astrogilda** [stanfordmlgroup/ngboost#147]
Hey @alejandroschuler!

In #76 you recommend that to obtain uncertainties on uncertanties (i.e. epistemic uncertainties), one could employ bagging. So for  a sample if I have `mu` and `sigma` from ngboost, and I'd like to find `sigma_on_mu`, `sigma_on_lower` and `sigma_on_upper`, I'd have to create `B` separate bootstrapped-bags, and combine their results. Specifically, you recommend training ngboost on each of these bags. However, afaik, bagging really only benefits if the different bags have uncorrelated results, and people typically use decision trees for this purpose since they are strong learners. Wouldn't using ngboost on the bags and combining their results fly in the face of these widely-practiced actions? Is there a more principled way to create 'bagged booster'?

**Comment by alejandroschuler** [comment]
The "benefits" of bagging that you are talking about are what you gain from using bootstrap methods to improve prediction via ensembling. My suggestion was to use the bootstrap for its original intended purpose, which is to estimate the variability that comes from sampling data. The point isn't to get better predictions, so it doesn't matter if the learners are weak or strong or correlated or whatever.

**Comment by alejandroschuler** [comment]
Relevant paper implementing exactly this idea (and an enhancement): https://arxiv.org/pdf/2006.10562.pdf

**Comment by astrogilda** [comment]
Fantastic! Reading it now :)

**Comment by astrogilda** [comment]
pity they haven't made their code opensource.
