### ISSUE TITLE
Save and load model

### ISSUE THREAD

**Issue by cavayangtao** [stanfordmlgroup/ngboost#15]
Hi, thank you for this repository. I'm using it in my work. I hope to know how to save and load the trained model. joblib.dump doesn't work.

**Comment by avati** [comment]
Hi @cavayangtao,

Thank you for giving ngboost a try. Have you tried the git HEAD version (by ``pip install --upgrade git+https://github.com/stanfordmlgroup/ngboost``? I recently fixed joblib saving in git.

**Comment by cavayangtao** [comment]
> Hi @cavayangtao,
> 
> Thank you for giving ngboost a try. Have you tried the git HEAD version (by `pip install --upgrade git+https://github.com/stanfordmlgroup/ngboost`? I recently fixed joblib saving in git.

Hi @avati, it works after update. Thx!
