### ISSUE TITLE
add a github release for 0.2.1

### ISSUE THREAD

**Issue by ryan-wolbeck** [stanfordmlgroup/ngboost#155]
Hey guys, 
I'd suggest adding a release for the current version in pypi to the github releases
https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-reposito
This would allow to track commits with the release tag so it's easy to see what code leads up to the release on pypi
Thanks,
Ryan

**Comment by tonyduan** [comment]
Thanks for the suggestion. I just created a new branch v0.2.1 and released it; this code reflects what's on PyPI.

I'm new to this so not 100% certain I've got everything right. If you have any further suggestions please do let us know!

**Comment by ryan-wolbeck** [comment]
@tonyduan looks good
