### ISSUE TITLE
Using k_categorical NGBClassifier as survival model

### ISSUE THREAD

**Issue by guyko81** [stanfordmlgroup/ngboost#157]
Hi,

I was thinking about a "kernel-ish" method for survival analysis, where we don't have an assumption about the shape of the survival curve. If the possible outcome time is integer and limited (in possible outcomes) it can be thought of as a simple multiclass classification but with censored data.
Would it be legit to update the k_categorical NGBClassifier distribution to be used for right-censored survival data? I was thinking something like

```
class CategoricalLogScoreCensored(LogScore):
    def score(self, Y):
        E = Y["Event"]
        T = Y["Time"]
        cens = (1 - E) * np.log(1 - np.sum([self.probs(t) for t in range(T)])
        uncens = E * -np.log(self.probs[T, range(len(T))])
        return -(cens + uncens)
```

Is my equation correct?

If you think this works then only the d_score should be calculated only? The metric remains the same?

Thanks!

**Comment by alejandroschuler** [comment]
You certainly can do something like that. I recommend reading [this](https://data.princeton.edu/wws509/notes/c7.pdf), paying particular attention to the last section on discrete-time survival analysis. It's well-wroth the investment to read it cover-to-cover, though. 

If you're saying the categorical probabilities represent the discrete-time hazards, and `self.probs` is `k * n`, then I think the NLL is
```
hazard = self.probs
cum_hazard = np.cumsum(hazard, axis=0)

nll = np.sum(
    - E * np.log(hazard[T, range(n)]) 
    + cum_hazard[T, range(n)]
)
```

With an appropriate `d_score` that should work. I think the metric can stay, yes.

**Comment by guyko81** [comment]
Thanks a lot! The book is very good!
