### ISSUE TITLE
Using CRPS score

### ISSUE THREAD

**Issue by RSChegani** [stanfordmlgroup/ngboost#160]
Hey,
I tried to use CRPS score by importing it and passing it to ngboost:
`from ngboost import NGBRegressor
from ngboost.distns import LogNormal, Normal
from ngboost.scores import CRPS, MLE

xgb = XGBRegressor(**param_set)
model = NGBRegressor(Base=xgb, learning_rate=0.1, verbose_eval=5, n_estimators=30, Dist=LogNormal, Score=CRPS())`

but I got an error. After a bit of digging I saw that the CRPS score is not implemented in `scores.py` and it's just a place holder. 
my questions are:

1. is my syntax to use crps score correct?
2. Where is the implementation of the score?

**Comment by tonyduan** [comment]
1. Actually I think you should replace the line with the following, see if it works:
```
model = NGBRegressor(Base=xgb, learning_rate=0.1, verbose_eval=5, n_estimators=30, Dist=LogNormal, Score=CRPS)`
```

2. The implementation of the score is specific to the distribution you're modeling with. So in your case it's in the implementation of [[lognormal.py]](https://github.com/stanfordmlgroup/ngboost/blob/master/ngboost/distns/lognormal.py).

**Comment by RSChegani** [comment]
Thanks @tonyduan for your quick reply. 
I'm still getting the following error:
----------------------------
TypeErrorTraceback (most recent call last)
<ipython-input-88-47f0e2916e5f> in <module>
      6 xgb = XGBRegressor(**param_set)
      7 model = NGBRegressor(Base=xgb, learning_rate=0.1, verbose_eval=5, n_estimators=30,Dist=LogNormal, Score=CRPS)
----> 8 model.fit(main_db[features], main_db[target]+100)#, X_val=val_set_1[features], Y_val=val_set_1[target])

~/anaconda3/lib/python3.7/site-packages/ngboost/ngboost.py in fit(self, X, Y, X_val, Y_val, sample_weight, val_sample_weight, train_loss_monitor, val_loss_monitor, early_stopping_rounds)
    157             loss_list += [train_loss_monitor(D, Y_batch)]
    158             loss = loss_list[-1]
--> 159             grads = D.grad(Y_batch, natural=self.natural_gradient)
    160 
    161             proj_grad = self.fit_base(X_batch, grads, sample_weight)

~/anaconda3/lib/python3.7/site-packages/ngboost/scores.py in grad(self, Y, natural)
      7 
      8     def grad(self, Y, natural=True):
----> 9         grad = self.d_score(Y)
     10         if natural:
     11             metric = self.metric()

~/anaconda3/lib/python3.7/site-packages/ngboost/api.py in d_score(self, Y)
     51                     return super().score(Y_from_censored(Y))
     52                 def d_score(self, Y):
---> 53                     return super().d_score(Y_from_censored(Y))
     54 
     55             class DistWithUncensoredScore(Dist):

~/anaconda3/lib/python3.7/site-packages/ngboost/distns/lognormal.py in d_score(self, Y)
     70                             2 * sp.stats.norm.cdf(Z) * sp.stats.norm.pdf(Z) ** 2 - \
     71                             np.sqrt(2/np.pi) * sp.stats.norm.pdf(np.sqrt(2) * Z))
---> 72         D[:, 1] = self.crps(Y) + (lT - self.loc) * D[:, 0]
     73         return D
     74 

TypeError: 'NoneType' object is not callable
------------------------------------------
My target value is a positive finite vector, in [75, 181] range, if it helps

**Comment by tonyduan** [comment]
@RSChegani Would you mind upgrading to v0.2.1, or to the GitHub master branch by running the following?
```
pip install --upgrade git+https://github.com/stanfordmlgroup/ngboost.git
```
Looks to me like this was a bug that was fixed in [[this commit]](https://github.com/stanfordmlgroup/ngboost/commit/f16fbd2324e9fc67a7a1be20375e114da001115e). Let us know if that works!

**Comment by RSChegani** [comment]
Thanks, @tonyduan I updated it, and it's working

**Comment by ryan-wolbeck** [comment]
Glad you got it working @RSChegani closing this
