### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by jagatsesh** [stanfordmlgroup/ngboost#164]
Hi

I was trying to install NGboost over python2.7. I have faced the following issue:

```
Collecting ngboost
  Using cached ngboost-0.2.2.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/jsc4104/environments/ml-iter-additive-2/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-MeqEew/ngboost/setup.py'"'"'; __file__='"'"'/tmp/pip-install-MeqEew/ngboost/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-Q6TJGy
         cwd: /tmp/pip-install-MeqEew/ngboost/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-MeqEew/ngboost/setup.py", line 5
        def get_version() -> str:
                          ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Can you please help me with it? I have scipy 1.2.3 installed.

Thanks
Jagat

**Comment by ryan-wolbeck** [comment]
@jagatsesh I'm thinking you'll have to use something like python 3.6, we should also have this explicit in the setup.py to check version (which I can do). I'll keep this open incase any of the other guys have a different suggestion. I just checked by building a new environment with 3.6 and didn't have this issue.

**Comment by jagatsesh** [comment]
Thank you for your reply.

Yes, I wil upgrade my modules to python 3.6+ very soon. And then let you know.

Jagat

--
Jagat Sesh Challa, Ph.D.
Postdoctoral ​Researcher
C​enter for Ultra-Scale Computing and Information Security
​Electrical and Computer Engineering Department
McCormick School of Engineering
Northwestern University, Evanston, IL

**Comment by ryan-wolbeck** [comment]
@jagatsesh thanks for pointing this out, I'll update the setup.py here shortly. It will make that more clear on install. I'm going to keep this issue open until that PR goes through
