### ISSUE TITLE
NGBoost Algorithm problem with shap.TreeExplainer

### ISSUE THREAD

**Issue by gerileka** [stanfordmlgroup/ngboost#167]
"""
Trying the new library for probabilistic regression and classifcation.
Minor problems when using the Shap explainer 

"""

#### SHAP plot for loc tree
import shap
shap.initjs()
explainer = shap.TreeExplainer(ngb, X, model_output=0)
shap_values = explainer.shap_values(X)
shap.dependence_plot(0, shap_values, X)

### Gives the following Error 

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-28-fe02832247d3> in <module>
      3 
      4 ## SHAP plot for loc trees
----> 5 explainer = shap.TreeExplainer(ngb, X, model_output=0)
      6 shap_values = explainer.shap_values(X)
      7 shap.dependence_plot(0, shap_values, X)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\explainers\tree.py in __init__(self, model, data, model_output, feature_dependence)
     87         self.feature_dependence = feature_dependence
     88         self.expected_value = None
---> 89         self.model = TreeEnsemble(model, self.data, self.data_missing)
     90 
     91         assert feature_dependence in feature_dependence_codes, "Invalid feature_dependence option!"

~\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\explainers\tree.py in __init__(self, model, data, data_missing)
    708             self.tree_output = "probability"
    709         else:
--> 710             raise Exception("Model type not yet supported by TreeExplainer: " + str(type(model)))
    711 
    712         # build a dense numpy version of all the tree objects

Exception: Model type not yet supported by TreeExplainer: <class 'ngboost.api.NGBRegressor'>

**Comment by ryan-wolbeck** [comment]
@gerileka My guess is the base learner you used isn't compatible. Can you share what that learner is?

**Comment by gerileka** [comment]
@ryan-wolbeck hi, thank you for your interests. I used the stock version from the user guide website, without change. 

### This is my full code

from ngboost import NGBRegressor

from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X, Y = load_boston(True)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

ngb = NGBRegressor().fit(X_train, Y_train)
Y_preds = ngb.predict(X_test)
Y_dists = ngb.pred_dist(X_test)

## Feature importance for loc trees
feature_importance_loc = ngb.feature_importances_[0]

## Feature importance for scale trees
feature_importance_scale = ngb.feature_importances_[1]

import shap
shap.initjs()
explainer = shap.TreeExplainer(ngb, model_output=0)

**Comment by ryan-wolbeck** [comment]
I spun up a colab notebook and was able to run it without error:
![image](https://user-images.githubusercontent.com/41489316/89807057-9cc5a100-dafd-11ea-810c-0729f260f1a7.png)

**Comment by gerileka** [comment]
@ryan-wolbeck Thank you. I tried as well and I think that is my version of shap. Installed it like last year, maybe I need an update on the library.
