### ISSUE TITLE
Categorical features?

### ISSUE THREAD

**Issue by kdlin** [stanfordmlgroup/ngboost#170]
Do categorical features require special treatment?

**Comment by alejandroschuler** [comment]
In its most generic form, NGBoost takes as its input a numerical matrix of predictors. Categorical features should therefore be represented by one-hot encoded or dummy variables. 

If you pass in a raw pandas dataframe, we use the [pre-processing from sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.utils.check_array.html) to transform that into a numeric matrix (see #129). That probably converts categorical columns into integers, which is not what you want. I don't like that behavior, but it's outside of our control. 

In theory, if you use regression trees as the base learner, then it should be possible to operate on categorical variables directly (e.g. [CatBoost](https://catboost.ai/)). Sklearn regression trees [do not implement this](https://stackoverflow.com/a/56857255). The only sensible thing to do is therefore to one-hot or dummy-encode your categories.
