### ISSUE TITLE
Laplace distribution calculation seems to be off

### ISSUE THREAD

**Issue by fengdai1234** [stanfordmlgroup/ngboost#177]
Our team is trying to leverage NGboost for our modeling working.
And I was trying to replicate the laplace distribution from the NGboost dev page.

Here is the calculation from WolframAlpha regarding the NLL derivative W.R.T to the location parameter, (scale parameter has been log transformed) 

original implementation: 
class LaplaceLogScore(LogScore): 
    
    def score(self, Y):
        return -self.dist.logpdf(Y)

    def d_score(self, Y):
        D = np.zeros((len(Y), 2)) # first col is dS/d𝜇, second col is dS/d(log(b))
        D[:, 0] = np.sign(self.logscale - Y)/self.scale
        D[:, 1] = 1 - np.abs(self.logscale - Y)/self.scale
        return D

our calculation:
D[:,0] = d/da -log(e^(-|x - a|/(e^b))/(2 e^b))

![Screen Shot 2020-09-01 at 3 18 11 PM](https://user-images.githubusercontent.com/8129761/91901808-5aa7ff00-ec66-11ea-9dae-6bda3d1d49ae.png)

e^b = scale, b = logscale.

Please take a look and see what could went wrong with our calculation.

Thanks

**Comment by alejandroschuler** [comment]
You're right- those should be:

```
def d_score(self, Y):
    D = np.zeros((len(Y), 2)) # first col is dS/d𝜇, second col is dS/d(log(b))
    D[:, 0] = np.sign(self.loc - Y)/self.scale
    D[:, 1] = 1 - np.abs(self.loc - Y)/self.scale
    return D
```

(note that `np.sign(self.loc - Y) = (self.loc - Y)/np.abs(self.loc - Y)` and that `np.exp(-self.logscale) = 1/self.scale`)

I'll change the documentation accordingly.
