### ISSUE TITLE
pred_dist(X_test).scale

### ISSUE THREAD

**Issue by jonathanhth** [stanfordmlgroup/ngboost#182]
Might be a silly question but what exactly does scale mean when I call the pred_dist function if I assume a normal distribution for my target variable using NGBRegressor? Is it the standard deviation or variance? Also on a side note I find official documentations for this package very lacking. It would be great if more documentations are published in addition to the user guide. Thank you nonetheless!

**Comment by avati** [comment]
Standard deviation. We use the same convention as scipy.stats.distribution for each distribution.
