### ISSUE TITLE
Do you consider supporting R language and Julia language?

### ISSUE THREAD

**Issue by xianglinZ** [stanfordmlgroup/ngboost#185]
I hope R language can be supported by this algorithm。

**Comment by alejandroschuler** [comment]
https://github.com/stanfordmlgroup/ngboost/issues/14

**Comment by alejandroschuler** [comment]
https://rstudio.github.io/reticulate/

**Comment by acca3003** [comment]
I have created a R version of NGBoost.
https://github.com/acca3003/ngboostR
It is a prelimiar version but you can test example.

**Comment by Akai01** [comment]
I have created an R interface which is supporting all APIs and their public methods:
https://github.com/Akai01/ngboost

Using R6 (OO programming in R) and reticulate (enables running Python in R)
