### ISSUE TITLE
Robust distributions (Student's t, Cauchy)

### ISSUE THREAD

**Issue by angeldroth** [stanfordmlgroup/ngboost#189]
Outlier resistance is a big use case in many fields of study, and over-dispersed normal distributions can help resist against them.

**Comment by astrogilda** [comment]
out of curiousity, could you give examples of applications where one might prefer student's t or cauchy over normal?

**Comment by angeldroth** [comment]
Any time you need robust regression (i.e. the conditional distribution has fat tails).
The application I am most familiar with is financial data.
