### ISSUE TITLE
Probabilistic quantile (P25) forecast - How to ?

### ISSUE THREAD

**Issue by nsankar** [stanfordmlgroup/ngboost#195]
Hi,

From an estimated forecast distribution (using ngboost regression), how can I get only the p25 (25th percentile) forecast? Can you guide with a code snippet and any other considerations to make . Thank you in advance.

**Comment by avati** [comment]
You could do something like this: 

```python
dists = ngb.pred_dist(X_test)
p25 = dists.ppf(0.25)
```

**Comment by nsankar** [comment]
thanks @avati
