### ISSUE TITLE
Jaxlib can't be installed under Windows

### ISSUE THREAD

**Issue by guyko81** [stanfordmlgroup/ngboost#2]
Collecting jaxlib
  Could not find a version that satisfies the requirement jaxlib (from versions: )
No matching distribution found for jaxlib

[https://github.com/google/jax/issues/507](https://github.com/google/jax/issues/507)

the issue raised under jax github page causes installation issues under Windows for this package

Would you consider releasing the PyTorch version too, I could make that work from the backup branch and the results look similar (though I'm not sure that the PyTorch implementation contains all the tricks from the jax version or not)

**Comment by abriosi** [comment]
I have the same problem under linux

![image](https://user-images.githubusercontent.com/23288462/66717502-9d07e980-edd1-11e9-91ab-ca53911f55ba.png)

**Comment by abriosi** [comment]
build jax using source https://jax.readthedocs.io/en/latest/developer.html#building-from-source

**Comment by tonyduan** [comment]
Linux users: we recommend building Jax from source as recommended by @abriosi.

Windows users: see [1], unfortunately this is out of scope for now.

[1] https://github.com/google/jax/issues/438

**Comment by abriosi** [comment]
@tonyduan How can we solve this for linux users? Does it have to be `jax` maintainers to corrected the linux python `.whl`?

**Comment by abriosi** [comment]
@tonyduan for linux users, if jaxlib install fails, they should run `pip install --upgrade pip`. Then `pip install ngboost` will work just fine

**Comment by avati** [comment]
Closing this issue now that the code runs without jax.

**Comment by Raviiisc** [comment]
> Closing this issue now that the code runs without jax.
Is there any solution to install jaxlib on windows? I am trying to run the following code which used jaxlib.
https://github.com/hanrach/p2d_fast_solver

I'd be grateful if someone can help me with this.
