### ISSUE TITLE
Possibly mistaken version of tqdm in requirements

### ISSUE THREAD

**Issue by synapticarbors** [stanfordmlgroup/ngboost#208]
I was fixing up the conda-forge recipe for `ngboost` and noticed that during the switch to `poetry`, the minimum version of `tqdm` was changed from `>=4.36.1` to `>=4.3`. The latter version of `tqdm` has no official release, but 4.4 was released in April of 2016. I'm wondering if the intended change was just to `>=4.36`?

**Comment by alejandroschuler** [comment]
@ryan-wolbeck @mzjp2

**Comment by ryan-wolbeck** [comment]
tqdm just creates a progress bar so I don't think we are tied to the functionality of 4.36 so I'm thinking we should just change it it to >= 4.4 since the current version is 4.51

**Comment by synapticarbors** [comment]
That's fine. I just wanted to make sure that there weren't any compatibility issues dropping to the much older version. 

https://tqdm.github.io/releases/

If there aren't any important api changes between 4.4 and 4.36, then I that's fine.
