### ISSUE TITLE
Add __version__ attribute to the package

### ISSUE THREAD

**Issue by cdagnino** [stanfordmlgroup/ngboost#21]
Hi,

I couldn't find any  __version__ attribute within the package.
I think it's helpful for bug reports to be able to do

```
import ngboost
print(ngboost.__version__)
```

**Comment by tonyduan** [comment]
Added, in [this](https://github.com/stanfordmlgroup/ngboost/commit/faa339a8b71c6398469b15860784382a6889a603) commit, thanks!
