### ISSUE TITLE
add github discussions

### ISSUE THREAD

**Issue by ryan-wolbeck** [stanfordmlgroup/ngboost#211]
I'm not sure who has permissions to allow GitHub discussions but I think it would be a nice tool for us to chat (outside of slack)

Example : https://github.com/vercel/vercel/discussions/3874

**Comment by ryan-wolbeck** [comment]
https://docs.github.com/en/free-pro-team@latest/discussions/quickstart

**Comment by alejandroschuler** [comment]
👍

**Comment by ryan-wolbeck** [comment]
Awesome, thanks @alejandroschuler
