### ISSUE TITLE
scikit-learn < 0.24

### ISSUE THREAD

**Issue by merl-dev** [stanfordmlgroup/ngboost#226]
Any particular reason for this?

**Comment by ryan-wolbeck** [comment]
I don't believe so other than locking the version based on when this logic was created. Do you have a follow up suggestion or request?

**Comment by merl-dev** [comment]
I was about to make the changes and submit a pull-request, but decided to run the tests on v0.3.7 first, to be sure, and found 2 fails
```
tests/test_distns.py::test_dists_runs_on_examples_crpscore[learner0-LogNormal] FAILED                                                                                     [ 47%]
tests/test_distns.py::test_dists_runs_on_examples_crpscore[learner0-Exponential] PASSED                                                                                   [ 50%]
tests/test_distns.py::test_dists_runs_on_examples_crpscore[learner1-Normal] PASSED                                                                                        [ 52%]
tests/test_distns.py::test_dists_runs_on_examples_crpscore[learner1-LogNormal] FAILED                                                                                     [ 55%]
```
Not sure if you're aware of these.  In any case, made the changes to `pyproject.toml` and making pull request since same errors showed up.

**Comment by acturner** [comment]
Any update on this - trying to use `poetry` to install packages that rely on `sklearn >= 0.24` is currently impossible.
