### ISSUE TITLE
Adding pickle to test?

### ISSUE THREAD

**Issue by MikeOMa** [stanfordmlgroup/ngboost#238]
is it worth adding:

```
serial = pickle.dumps(ngb)
ngb = pickle.loads(serial)
ngb.predict(X_test)
```
To `test_distns.py` for most of the tests? I know I use pickle all the time when I'm using ngboost/sklearn so ensuring that everything can pickle seems sensible to me. 

Happy to do this if nobody else was already planning to and you think it is a good idea.

**Comment by ryan-wolbeck** [comment]
@MikeOMa I started going down this  road a while ago here https://github.com/stanfordmlgroup/ngboost/compare/test-pickle but didn't get finished with it. If you have time your welcome to pick up where I left off. Generally think this is something that needs to get done

**Comment by MikeOMa** [comment]
I did see this branch after starting the issue, I was going to try to fix the Survival Pickling when I have a chance so I can add it in with that pull request. Probably won't be for a week or two though.
