### ISSUE TITLE
Calculate confidence-interval for regression.

### ISSUE THREAD

**Issue by satya-pattnaik** [stanfordmlgroup/ngboost#252]
Can we have a built in function to calculate confidence interval for regression.
```
X = load_data()
....
distribution = ngboost.pred_dist(X)
conf_int = scipy.stats.norm.interval(0.95, loc=distribution.loc, scale=distribution.scale)
```
This is obviously for normal distribution, but is there some way we can implement this for the
most popular distributions, this will help.

**Comment by creatornadiran** [comment]
Can we use bootstrap for this?

**Comment by satya-pattnaik** [comment]
We can use bootstrap and that is one of the ideal solutions, but in this case we already have the conditional distribution information, SO why not use the intervals out of it.

**Comment by creatornadiran** [comment]
You are right, it makes sense

**Comment by MikeOMa** [comment]
I think this does work already for a subset of the distributions like so:

```
import numpy as np
import ngboost as ngb
X= np.random.randn(500,2)
y = np.random.randn(500)
model = ngb.api.NGBRegressor(n_estimators=5)
model.fit(X,y)
pred = model.pred_dist(X)
lower, upper = pred.interval(0.95)
```

Most distributions are implemented such that the method is not defined in dir(pred), it searches for the method in the scipy implementation. So if the method is defined in scipy it will be defined for the output of `model.pred_dist(X)`

I think multivariate normal is the only regression distribution that this does not work for but I could be wrong!
