### ISSUE TITLE
Future Warning when running the examples

### ISSUE THREAD

**Issue by JoseLlorensRipolles** [stanfordmlgroup/ngboost#254]
Hi, 

This package looks amazing, thank you! 

When you run the examples, a future warning is raised concerning how the toy datasets are loaded from sklean:

`
venv/lib/python3.9/site-packages/sklearn/utils/validation.py:67: FutureWarning: Pass return_X_y=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "`

As the warning suggest, going from `X, Y = load_boston(True)` to `X, Y = load_boston(return_X_y=True)` fix the warning and avoid the future error. This issue raises a few times in code and docs, so I thought I would just notify it rather than pushing a PR in case you don't want to change it.

Thank you in advance!

**Comment by alejandroschuler** [comment]
Thanks for the heads up! Do feel free to submit a PR, otherwise we'll get around to it one day :)
