### ISSUE TITLE
How extract survival functions from NGBSurvival.pred_dist 

### ISSUE THREAD

**Issue by CoteDave** [stanfordmlgroup/ngboost#255]
Hi, 

Is there an easy way to extract the survival functions from each individual instance with the NGBSurvival.pred_dist ?

Thanks!

**Comment by CoteDave** [comment]
I think this can do the job ?

survival_func_list = []
for i in range(0, np.max(y_train['DUREE_MOIS'])):
    survival_func_list.append(y_dists.sf(i))
survival_func_matrix = pd.DataFrame(survival_func_list)

**Comment by alejandroschuler** [comment]
@CoteDave, also see this discussion: https://github.com/stanfordmlgroup/ngboost/discussions/224
