### ISSUE TITLE
cannot import Bernoulli from ngboost.distns

### ISSUE THREAD

**Issue by iopkelvin** [stanfordmlgroup/ngboost#26]

**Comment by tonyduan** [comment]
Apologies, the version with the Bernoulli distribution is still in development and hasn't been pushed to PyPI yet.

In the meantime could you try installing with the following and try again:

`
pip3 install git+https://github.com/stanfordmlgroup/ngboost
`

Let us know if that works!

**Comment by iopkelvin** [comment]
Hi Tony,
I tried that as well, but it doesn’t work."

cannot import name 'Bernoulli' from 'ngboost.distns' (/Users/kelvin/anaconda3/lib/python3.7/site-packages/ngboost/distns/__init__.py)

Best,
Kelvin

**Comment by avati** [comment]
Hi @iopkelvin, I remember you from cs229! good to see you again!

I just checked again and the code works fine for me for Bernoulli. Perhaps you need to try

```
pip install --upgrade git+https://github.com/stanfordmlgroup/ngboost
```
?

**Comment by iopkelvin** [comment]
Prof Avati,
I was very happy to realize that you created the new algorithm. I’m very excited of trying it out on my project.
I’m giving a short presentation of different gradient boosting models, and showing Natural Gradient Boosting.

Prof, I’m trying it now.
I have a question. For Bernoulli (in classification), I have the option ngb.pred_dist(x_test), and then get the .prob of the result.
This gives the probability predictions.
How can I get the actual predictions. As .predict(x_test) gives me "'NoneType' object has no attribute ‘flatten’"

Can I use the probability predictions from .pred_dist > .prob, and then use the probabilities to select the predictions based on a threshold?

Thank you,

**Comment by avati** [comment]
You can certainly use ngb.pred_dist(x_test) 

I don't know why the NoneType error is happening. Do you have a simple test script to reproduce that error?

**Comment by avati** [comment]
Closing this issue for now as it is not reproducible. Please re-open if you encounter it again.
