### ISSUE TITLE
How to perform Concordance Index and Brier score prediction for NGBoost survival?

### ISSUE THREAD

**Issue by cadrev** [stanfordmlgroup/ngboost#269]
Hello, I'd like to ask if there is a way to compute both C-Index and Brier Scores for the survival predictions?

**Comment by alejandroschuler** [comment]
NGBoost gives you back a full predicted distribution. If you want to get metrics for point predictions, you should first extract the point predictions (e.g. by taking the mean of the predicted distributions for each observation) and then use standard packages (e.g. `sklearn.metrics`) to compute the metrics you want.
