### ISSUE TITLE
What are the limitations to add a base learner?

### ISSUE THREAD

**Issue by civilinformer** [stanfordmlgroup/ngboost#28]
I would like to know what are the limitations in adding base learners. I see in ngboost/ngboost/learners.py only two learners implemented, each taken from sklearn. Is it the case that we can add **any** base learner from sklearn simply by adding to this file some learner and the specifying it at NGBoost instantiation time? If this is not the case what is the limitation? Why aren't more base learners implemented?

**Comment by civilinformer** [comment]
I went ahead and cloned the distribution and hacked into it and tried it with a different non-linear base learner and it indeed worked. Thanks for working on this! It is very interesting. 

I am puzzled by why the results differ so much between runs but I'll save that for a different issue down the road.

**Comment by avati** [comment]
Yes any base learner will work. Not all base learners give good performance with boosting, but it should work nonetheless.
