### ISSUE TITLE
Bump supported python version

### ISSUE THREAD

**Issue by robertsont** [stanfordmlgroup/ngboost#285]
Hi All,

NGBoost currently supports python version 3.6.0 per [this line](https://github.com/stanfordmlgroup/ngboost/blob/51a299197ae77dff88826156edf386313201d99b/pyproject.toml#L16). Pandas versions 1.0.0 and upwards, however, require at least python 3.6.1 or higher ([see here](https://github.com/pandas-dev/pandas/blob/fd9ceb9dce3d62d8a9caa6ba7c127b512939452e/setup.py#L768)). Supporting python 3.6.0 specifically is forcing the project to use a version of Pandas that is about two and a half years old. I'm actually having trouble running `poetry install` locally on Ubuntu 18.04.6 with python 3.9.1 due to (seemingly) the poetry dependency solver not correctly identifying the necessary version of numpy to build with this older version of pandas.

I propose increasing the minimum supported python version to 3.6.1 and would be happy to submit a PR accomplishing this, provided there's no problem with abandoning support for python 3.6.0.

**Comment by alejandroschuler** [comment]
A PR would be great! I don't think there's any reason not to bump the python version- @ryan-wolbeck does that sound right?

**Comment by ryan-wolbeck** [comment]
@alejandroschuler yeah I think it's worth bumping here, I'm having the same issue as @robertsont when trying to build from 3.9. Thanks for the contribution @robertsont!
