### ISSUE TITLE
empirical used retrain not refit as paper

### ISSUE THREAD

**Issue by aprilffff** [stanfordmlgroup/ngboost#3]
It seesm the empirical results used retrain model (changing tree structures) but not refit (keep pretrained tree structures)  in "ngboost/examples/empirical/regression.py". However, the paper said exactly "refit" which is more reasonable

**Comment by avati** [comment]
Sorry, wasn't aware of the distinction between 'refit' and 'retrain' in trees. I guess the paper actually means 'retrain' in this terminology (will update it for the next version).
