### ISSUE TITLE
Slide deck not accessible

### ISSUE THREAD

**Issue by turtlemonvh** [stanfordmlgroup/ngboost#328]
Similar to https://github.com/stanfordmlgroup/ngboost/issues/84, the deck seems to be inaccessible again.

From https://github.com/stanfordmlgroup/ngboost; the link is https://drive.google.com/file/d/183BWFAdFms81MKy6hSku8qI97OwS_JH_/view?usp=sharing

Which gives

![image](https://user-images.githubusercontent.com/889442/231547671-34223e90-7ff0-40d8-9efd-52d8c506fbf1.png)

**Comment by alejandroschuler** [comment]
ah, my bad. new link is here: https://docs.google.com/presentation/d/1Tn23Su0ygR6z11jy3xVNiLGv0ggiUQue/edit?usp=share_link&ouid=102290675300480810195&rtpof=true&sd=true

**Comment by turtlemonvh** [comment]
Thanks @alejandroschuler - looks like the link works fine again. Thanks for the quick fix!
