### ISSUE TITLE
AttributeError with np.bool when fitting NGBRegressor with Exponential distribution

### ISSUE THREAD

**Issue by DumasCharles** [stanfordmlgroup/ngboost#336]
Package Name: ngboost
Package Version: 0.4.1
Operating System: Windows
Python Version: 3.10

When I try to fit a `NGBRegressor` with `Dist=Exponential`. I get the `AttributeError` below:

```
raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
```
This is the same issue as mentioned in #331 , and I understand it will be resolved with #320. But the numpy deprecation leads to an Error and not a Warning, so it is quite critical.

Thank you :)

**Comment by ryan-wolbeck** [comment]
I agree, thanks for the note. I've provided an update on the findings I'm working through here: https://github.com/stanfordmlgroup/ngboost/pull/320#issuecomment-1767431999

**Comment by ryan-wolbeck** [comment]
This should be fixed but let us know if you still have issues

pip install ngboost==0.4.2

**Comment by DumasCharles** [comment]
Yes it works now, thank you very much for acting quickly on this!
