### ISSUE TITLE
Support for Incremental Learning?

### ISSUE THREAD

**Issue by john-woolley** [stanfordmlgroup/ngboost#342]
I was wondering if a partial_fit method is possible for this algorithm similar to some of the scikit-learn API models or analogous to the update method of Light GBM.

**Comment by alejandroschuler** [comment]
it's already implemented, you can see here: https://github.com/stanfordmlgroup/ngboost/blob/07734dd16013d745a329241ad9eea0a0e53d784b/ngboost/ngboost.py#L262. May be that the docs need more details about this or it needs to be cleaned up for the API so feel free to put in a PR if you like.
