### ISSUE TITLE
Discrete explanatory variables

### ISSUE THREAD

**Issue by patrickocal** [stanfordmlgroup/ngboost#351]
Before I dive in and start using this codebase, I have the following question. In the paper, it suggests that, although we have freedom over the domain of the dependent variable, we have $x \in R^n$. So am I to interpret this as meaning that $x$ is required to be a real-valued random vector? That is, discrete explanatory variables are excluded?

*Just a quick yes/no would be much appreciated as the the author (of the paper) is taking a while to answer.*

**Comment by patrickocal** [comment]
To try and answer my own question: I can't see why we need $x$ to be real-valued, since the natural gradient pertains to the dual, parameter space. So, are we to assume that one-hot representations of discrete/categorical variables are in? I can see that we have one-hot representations here:
https://github.com/stanfordmlgroup/ngboost/blob/38c2245c400a69b8885e08c63a38dcf4224267cc/examples/experiments/survival_exp.py#L73

If so, then I suggest changing the paper as it is misleading.

**Comment by patrickocal** [comment]
Okay, so the minimum working example answers this: there are discrete (if not categorical variables) in X.

**Comment by alejandroschuler** [comment]
Yes, discrete features are supported. $x \in \mathbb R^p$ is not misleading because, for example, $x \in \\{0,1\\} \subset \mathbb R^p$

**Comment by patrickocal** [comment]
Okay, the fact that $\{0, 1\} $ is a subset of the reals is not the point, mate: obviously.
It is the statement $x\in \R$ alongside the language (in the paper) used to describe the dependent variable: (why do you bother stating $y\in \{ 0, 1\} $? This is what makes the paper misleading: to mathematician anyway.

**Comment by alejandroschuler** [comment]
🙄
