### ISSUE TITLE
Do you have any plans to use Github Actions?

### ISSUE THREAD

**Issue by wakamezake** [stanfordmlgroup/ngboost#36]
I want to continue testing (e.g. #35) with [Github Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions).

**Comment by avati** [comment]
I'm not familiar with Github Actions. What needs to be done by me for you to use it?

**Comment by wakamezake** [comment]
Invite me to repository collaborators because only repository collaborators may create workflows in GitHub Actions.
[Github - inviting-collaborators-to-a-personal-repository](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository)

**Comment by alejandroschuler** [comment]
I'm going to merge this issue into the unit testing issue- right now there is a lot to be done on that front but I'm going to prioritize getting a clean codebase and set of usable features before going back and writing tests.
