### ISSUE TITLE
Scripts are not working

### ISSUE THREAD

**Issue by wakamezake** [stanfordmlgroup/ngboost#43]
[NGBoost Scripts](https://github.com/stanfordmlgroup/ngboost/tree/master/scripts) are not working because renaming and moving files.

This Link is result of executing the script.
[Google Colabratory - execute NGBoost Scripts](https://colab.research.google.com/drive/11rY_pqR1DOBzr6O9IxAx_DS5aWv7vxEX)

**Comment by tonyduan** [comment]
Ah, good point -- thank you! Pushed a fix to master.
