### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by ChingzhiWU** [stanfordmlgroup/ngboost#45]
Collecting git+https://github.com/stanfordmlgroup/ngboost.git
  Cloning https://github.com/stanfordmlgroup/ngboost.git to c:\users\stig.cz\appdata\local\temp\pip-req-build-zjnf7vpn
  Running command git clone -q https://github.com/stanfordmlgroup/ngboost.git 'C:\Users\Stig.CZ\AppData\Local\Temp\pip-req-build-zjnf7vpn'
  error: RPC failed; curl 18 transfer closed with outstanding read data remaining
  fatal: the remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
ERROR: Command errored out with exit status 128: git clone -q https://github.com/stanfordmlgroup/ngboost.git 'C:\Users\Stig.CZ\AppData\Local\Temp\pip-req-build-zjnf7vpn' Check the logs for full command output.

**Comment by tonyduan** [comment]
Huh, looks to be an RPC issue? Doesn't seem to have anything to do with the codebase. 

Could you try installing via PyPI and see if that works?

pip3 install ngboost

**Comment by ChingzhiWU** [comment]
I am very glad to hear from you
I have solved the installation problem, and I am greatly looking forward to more practical examples of ngboost.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tony Duan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 凌晨1:29
收件人:&nbsp;"stanfordmlgroup/ngboost"<ngboost@noreply.github.com&gt;;
抄送:&nbsp;"Stig "<736388414@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [stanfordmlgroup/ngboost] I can't install it (#45)




Huh, looks to be an RPC issue? Doesn't seem to have anything to do with the codebase.
 
Could you try installing via PyPI and see if that works?
 
pip3 install ngboost

**Comment by tonyduan** [comment]
Great, closing this issue.
