### ISSUE TITLE
Any plan for model explanation functionality?

### ISSUE THREAD

**Issue by zhiruiwang** [stanfordmlgroup/ngboost#5]
Read the paper and tried this package, had to say it is marvelous! I will not hesitate to use it in my real-life work, but wonder if there is plan to add support for model explanation tool such as feature importance plot, SHAP plot or tree visualizer. It would be crucial to present the model explanation to business stakeholders.
Thanks for this fantastic masterpiece!

**Comment by avati** [comment]
Hi @zhiruiwang, ngboost is still in very early stage of development. We are working on several features and speedup changes. It is very likely that something like feature importance might be added down the line. We also welcome contributions :-)

**Comment by zhiruiwang** [comment]
@avati I have made a [pull request](https://github.com/stanfordmlgroup/ngboost/pull/27) of feature importance plot for DecisionTreeRegressor using similar API as sklearn. I will also make a pull request to SHAP and add in SHAP support for NGBoost.

**Comment by zhiruiwang** [comment]
SHAP support added to the same pull request #27

**Comment by alejandroschuler** [comment]
https://github.com/stanfordmlgroup/ngboost/pull/57
https://github.com/stanfordmlgroup/ngboost/pull/58
