### ISSUE TITLE
implement categorical distribution for multiclass classification

### ISSUE THREAD

**Issue by alejandroschuler** [stanfordmlgroup/ngboost#56]

**Comment by alejandroschuler** [comment]
https://github.com/stanfordmlgroup/ngboost/commit/87386b69f9eeba9e0f65c4afc4e8e7b187df0c2c

Notes:
- To make this work with the existing code (which assumes each distribution has a fixed number of parameters), the categorical distribution with K classes is generated by a class factory function so the model is instantiated like: `ngb = NGBClassifier(Dist=k_categorical(3))`
- The array of outcomes `Y` should be an integer array with values from 0 to K indicating the number of the class that `Y[i]` takes, as is standard in sklearn.

still to do:
- fix the `predict` method for NGBClassifier to work for multiclass problems
- implement CRPS score for categorical distribution
- write an example script
- input validation? (should be a thing more generally, will probably open another issue for this)

**Comment by alejandroschuler** [comment]
note: may also want to change the distributions accepting the transpose of the params... makes the code annoying

**Comment by chemadix** [comment]
if my k classes were defined from a number different from "0" (e.g. from 1 to 10); how can the paremeter Dist can be modified? Is it necesary to use k_categorical?

**Comment by alejandroschuler** [comment]
@chemadix it is a requirement that the classes be 0,1,2... K-1 for `Dist=k_categorical(K)`. You have to transform your Y so they are numbered that way before running ngboost. In the case you describe, just take `Y=Y-1`.
