### ISSUE TITLE
Feature importance

### ISSUE THREAD

**Issue by CarlitosDev** [stanfordmlgroup/ngboost#62]
Hi, 
First of all, many thanks for **ngboost**.

The issue I'm reporting is related to the feature importances property. When I try to get this property, unfortunately the returned value is **None**. I believe this is due to the following if clause:
`if not 'sklearn.tree.tree.DecisionTreeRegressor' in str(type(self.base_models[0][0])):
            return None`
In sklearn version **0.22**, `str(type(self.base_models[0][0]))` returns `<class 'sklearn.tree._classes.DecisionTreeRegressor'>`

For me, it works if I replace the clause by
`if not isinstance(self.base_models[0][0], sklearn.tree.DecisionTreeRegressor):`

Can you please check if you also have this problem?

Many thanks,
Carlos

**Comment by alejandroschuler** [comment]
Hey @CarlitosDev, I think your solution is good. If you make a pull request with that change I'll accept it.

**Comment by alejandroschuler** [comment]
https://github.com/stanfordmlgroup/ngboost/pull/63
