### ISSUE TITLE
Add support for GridSearchCV

### ISSUE THREAD

**Issue by YMMS** [stanfordmlgroup/ngboost#7]
Thanks for your work sharing. Maybe it is necessary to add support for GridSearchCV of scikit-learn to improve the usability and influence.

**Comment by avati** [comment]
Thank you for the pull request @YMMS. I am not yet familiar with GridSearchCV API, but I imagine it can be useful and important. I will mark this as an enhancement, and also encourage others to give it a shot at implementation before I get to it 😄

**Comment by tonyduan** [comment]
Think we can close this issue now, see the file examples/sklearn_cv.py which uses GridSearchCV.
