### ISSUE TITLE
Decoupling Aleatoric vs. Epistemic Uncertainty

### ISSUE THREAD

**Issue by ogencoglu** [stanfordmlgroup/ngboost#76]
Thanks for the great work!

Is there any way to estimate _aleatoric_ and _epistemic_ uncertainties separately with this method?

**Comment by alejandroschuler** [comment]
Thanks @ogencoglu! 

If I understand the question, NGBoost estimates only aleatoric uncertainty. This is the difference between a confidence interval and a prediction interval. NGBoost can be used to construct the latter, but not the former. My post on prediction intervals discusses this:
https://towardsdatascience.com/interpreting-the-probabilistic-predictions-from-ngboost-868d6f3770b2

If you want to instead estimate a confidence interval (e.g. for mu(x) or sigma(x)), I would use a bootstrap method on top of NGBoost: generate a bunch of size-N samples from your data and rerun ngboost on all of them to generate a sampling distribution for mu(x), or whatever parameter. 

Let me know if that's unclear to you and I'll do my best to clarify.
