### ISSUE TITLE
Fixing error

### ISSUE THREAD

**Issue by arkp1612** [stanfordmlgroup/ngboost#77]
Encountering this error repeatedly - "type object 'LogNormal' has no attribute 'scores' ". How can I fix it?

**Comment by tonyduan** [comment]
Apologies, we just made some recent refactors -- I just made some updates to the survival regression code to reflect these changes.

@arkp1612 Could you re-pull from master and try this again? If you could provide code for us to reproduce the issue that would be helpful was well.

**Comment by alejandroschuler** [comment]
Yes, exactly. Out of curiosity @arkp1612, are you using this distribution for a regular regression problem or for survival?

**Comment by arkp1612** [comment]
@tonyduan I tried it again but still it's not working. I'm unable to share the code due to confidentiality restrictions. However, running the code given in kaggle - https://www.kaggle.com/s903124/ngboost-for-nfl-data presents the same error. 

This is the error that comes up - 
IndexError                                Traceback (most recent call last)
<ipython-input-14-0ad390fc302a> in <module>()
----> 1 ngb.fit(X_train,(y_train-min(y_train)+0.001))

~/anaconda3/envs/python3/lib/python3.6/site-packages/ngboost/ngboost.py in fit(self, X, Y, X_val, Y_val, train_loss_monitor, val_loss_monitor)
     71         loss_list = []
     72         val_loss_list = []
---> 73         self.fit_init_params_to_marginal(Y)
     74 
     75         params = self.pred_param(X)

~/anaconda3/envs/python3/lib/python3.6/site-packages/ngboost/ngboost.py in fit_init_params_to_marginal(self, Y, iters)
    123 
    124     def fit_init_params_to_marginal(self, Y, iters=1000):
--> 125         self.init_params = self.Dist.fit(Y)
    126         return
    127 

~/anaconda3/envs/python3/lib/python3.6/site-packages/ngboost/distns/lognormal.py in fit(Y)
     89 
     90     def fit(Y):
---> 91         T = Y["Time"]
     92         m, s = sp.stats.norm.fit(np.log(T))
     93         return np.array([m, np.log(s)])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Another error that I encountered is - Key Error: 'Time' which occurs at the same line 
---> 91         T = Y["Time"]

It would really help if I could get a way around it. I am attempting to give a probabilistic sales 
forecast at my company (to answer @alejandroschuler 's question) , and was really excited to come across Ngboost and am equally eager to implement it! It works for Normal Distribution, but I also want to try it for some skewed distributions.

**Comment by alejandroschuler** [comment]
@arkp1612 ah, the issue is that right now the lognormal is only configured for survival problems, not general purpose regression. However, that restriction is easily removed- I'll fix it for you today.

**Comment by alejandroschuler** [comment]
@arkp1612 https://github.com/stanfordmlgroup/ngboost/tree/survivial-regression-integration should solve your problem. It's not pushed to master yet because I still want to make sure this approach is ok with the rest of the dev team but feel free to pull that branch and use it. I'll leave this issue open until we've finalized the changes and pulled into master.

**Comment by alejandroschuler** [comment]
I've integrated the changes into master- let me know if you keep having issues and please have a look at our new [vignette](https://github.com/stanfordmlgroup/ngboost/blob/master/examples/vignette.ipynb) to see some examples.
