### ISSUE TITLE
Sorry，it couldn't install ngboost under Windows

### ISSUE THREAD

**Issue by ranranV** [stanfordmlgroup/ngboost#8]
pip install ngboost
Collecting ngboost
  Using cached https://files.pythonhosted.org/packages/58/15/8942e2b8a38f92b92e1dedad882b0746372e4acde236e74b98bfa66d717a/ngboost-0.1.3-py3-none-any.whl
Collecting scikit-learn>=0.21.3
  Using cached https://files.pythonhosted.org/packages/76/79/60050330fe57fb59f2c53d0d11673df28c20ea9315da3652477429fc4949/scikit_learn-0.21.3-cp36-cp36m-win_amd64.whl
Collecting numpy>=1.17.2
  Using cached https://files.pythonhosted.org/packages/55/7a/f32b39164262765b069b0fe3ec5d4b47580c9c60f7bd3588b58ba8e93a4c/numpy-1.17.3-cp36-cp36m-win_amd64.whl
ERROR: Could not find a version that satisfies the requirement jaxlib>=0.1.29 (from ngboost) (from versions: none)
ERROR: No matching distribution found for jaxlib>=0.1.29 (from ngboost)

**Comment by ranranV** [comment]
pip install ngboost
Collecting ngboost
  Using cached https://files.pythonhosted.org/packages/58/15/8942e2b8a38f92b92e1dedad882b0746372e4acde236e74b98bfa66d717a/ngboost-0.1.3-py3-none-any.whl
Collecting scikit-learn>=0.21.3
  Using cached https://files.pythonhosted.org/packages/76/79/60050330fe57fb59f2c53d0d11673df28c20ea9315da3652477429fc4949/scikit_learn-0.21.3-cp36-cp36m-win_amd64.whl
Collecting numpy>=1.17.2
  Using cached https://files.pythonhosted.org/packages/55/7a/f32b39164262765b069b0fe3ec5d4b47580c9c60f7bd3588b58ba8e93a4c/numpy-1.17.3-cp36-cp36m-win_amd64.whl
ERROR: Could not find a version that satisfies the requirement jaxlib>=0.1.29 (from ngboost) (from versions: none)
ERROR: No matching distribution found for jaxlib>=0.1.29 (from ngboost)

**Comment by avati** [comment]
Could you try the git version?

```
pip install git+https://github.com/stanfordmlgroup/ngboost
```

**Comment by ranranV** [comment]
> Could you try the git version?
> 
> ```
> pip install git+https://github.com/stanfordmlgroup/ngboost
> ```
