### ISSUE TITLE
The tree learner that changed the parameters is not callable

### ISSUE THREAD

**Issue by ShirleyLiu1020** [stanfordmlgroup/ngboost#82]
The following problem occurs when changing the parameters of the base learner. The default is a depth-3 regression tree. If I use the default tree, there is no problem.
ngb = NGBRegressor(Base=DecisionTreeRegressor).fit(X_train, y_train)

But if I change the depth of the learner like this,
ngb = NGBRegressor(Base=DecisionTreeRegressor(criterion='friedman_mse', max_depth=4)).fit(X_train, y_train)
I will get a TypeError: 'DecisionTreeRegressor' object is not callable. Why is that?

**Comment by alejandroschuler** [comment]
Hi @ShirleyLiu1020, I'm not able to replicate your error- the code you supplied works just fine for me. Are you sure you have the most recent version of the code? Use `pip install --upgrade git+https://github.com/stanfordmlgroup/ngboost.git` to make sure.

**Comment by ShirleyLiu1020** [comment]
I checked that my version is 0.1.5dev and tried the code you gave. But the terminal reported `ERROR: Command errored out with exit status 1: git clone -q https://github.com/stanfordmlgroup/ngboost.git /private/var/folders/69/9qgttlg95xx58m395h4_d0xc0000gn/T/pip-req-build-rhvlg93y Check the logs for full command output.`

**Comment by alejandroschuler** [comment]
The version number hasn't been updated consistently yet so unfortunately that's not of much use. But I'm still sure it's a version issue since the code works fine for me. 

I don't know why you're not able to upgrade with pip. Maybe try `pip3`? You can also try uninstalling and then downloading the code manually (or fork and clone) from GitHub and then adding whatever directory you put the code in to your pythonpath before importing.

**Comment by ShirleyLiu1020** [comment]
Ok, thank you very much for your answer. I'll try it.

**Comment by alejandroschuler** [comment]
We've also just updated the version on pypi so a normal `pip install --upgrade ngboost` should now get you the latest code.

**Comment by ShirleyLiu1020** [comment]
Wonderful! This is extraordinarily helpful. Much appreciated.

**Comment by alejandroschuler** [comment]
Sure thing, happy to help. I'm going to close the issue for now but let me know if you still need a hand with anything.
