### ISSUE TITLE
could not broadcast input array from shape (0,360000) into shape (1,360000)

### ISSUE THREAD

**Issue by informatica92** [stanfordmlgroup/ngboost#83]
Hi all, 
I am trying to test NGBoost on one of my dataset but I am getting a not easy to understand error and it is: 
could not broadcast input array from shape (0,360000) into shape (1,360000)

The type and the preview of the dataset is:
![image](https://user-images.githubusercontent.com/17550961/74166755-6c24ad80-4c27-11ea-9db1-c05e5f71c21b.png)

While the code I am trying to execute is:
![image](https://user-images.githubusercontent.com/17550961/74167029-e48b6e80-4c27-11ea-9a66-51f1e75fc0c6.png)

Moreover, if I try to run the example code I used to get this snippet, it runs without any problem

**Comment by tonyduan** [comment]
@informatica92 Could you print the shapes of `data_dataset` and `target_dataset`?

**Comment by informatica92** [comment]
![image](https://user-images.githubusercontent.com/17550961/74228629-20bedd80-4cc1-11ea-80ef-666d5ea8101b.png)
Hi @tonyduan, these are the shapes of the variables you asked me

**Comment by tonyduan** [comment]
@informatica92 Since we're unable to reproduce this error, can you attach the notebook you're using? It would greatly help us debug.

**Comment by alejandroschuler** [comment]
@informatica92 any luck with this?
