### ISSUE TITLE
LogNormal CRPScore doesn't work

### ISSUE THREAD

**Issue by alejandroschuler** [stanfordmlgroup/ngboost#86]
```
X, Y = load_boston(True)
X_reg_train, X_reg_test, Y_reg_train, Y_reg_test = train_test_split(X, Y, test_size=0.2)

NGBRegressor(Dist=LogNormal, Score=CRPScore).fit(X_reg_train, Y_reg_train) 
```

gives `ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 404 is different from 2)` in `np.linalg.solve`. See: https://github.com/stanfordmlgroup/ngboost/runs/440525418?check_suite_focus=true

**Comment by alejandroschuler** [comment]
also happens for `NGBSurival`

**Comment by tonyduan** [comment]
Thanks for finding this bug. Think I fixed it with [[this]](https://github.com/stanfordmlgroup/ngboost/commit/74f2f90cc2839a5414b177034e634c4b6f9fb755) commit, PTAL.

**Comment by alejandroschuler** [comment]
tests pass, so I'll close this. Thanks!!
