### ISSUE TITLE
pickling error for NGBClassifier

### ISSUE THREAD

**Issue by jfb10d** [stanfordmlgroup/ngboost#92]
Got the following error when pickling a trained model:
`AttributeError: Can't pickle local object 'k_categorical.<locals>.Categorical'`

And here's the code:
```
PARAMS = {'Dist': Bernoulli,'Score': LogScore, 'verbose': verbose,
                  'n_estimators':1500}
ngb = NGBClassifier(**PARAMS)
bst = ngb.fit(X, y, X_test, y_test,early_stopping_rounds=50)
print("Writing trained model file: {}".format(trainedModelFile))
with open(trainedModelFile,'wb') as f:
    pickle.dump(bst,f)
```

Thanks for looking into it in advance!

**Comment by alejandroschuler** [comment]
I think I got it with https://github.com/stanfordmlgroup/ngboost/commit/0c51f1444c5c8bfa12e94cb96177caa730ad26df, but let me know if it still doesn't work for you after updating.
