### ISSUE TITLE
Automatic version numbering?

### ISSUE THREAD

**Issue by alejandroschuler** [stanfordmlgroup/ngboost#99]
@wakamezake @daikikatsuragawa thank you both for all your recent help with the package infrastructure! 

One thing that is bugging me is that I *always* forget to update the version number when I push changes. Do you know of a framework or set of pre-commit hooks that would solve this problem? It seems like [GitVersion](https://github.com/GitTools/GitVersion) might be what I'm looking for but I don't really understand the ins and outs and I'm not sure it's compatible with `pre-commit`.

**Comment by daikikatsuragawa** [comment]
That's very good idea!
But I don't understand how to use GitVersion. 😰

**Comment by daikikatsuragawa** [comment]
I'll look into it!

**Comment by daikikatsuragawa** [comment]
For the time being, I would like to respond to the following. What do you think?

- Make [this code](https://github.com/stanfordmlgroup/ngboost/blob/master/setup.py#L5) in setup.py a variable.
- Then, it is made to correspond to the value of [ngboost/__init__.py /](https://github.com/stanfordmlgroup/ngboost/blob/master/ngboost/__init__.py#L4).

Specifically, When reading variables, `dev` is deleted and a value obtained by subtracting a number is substituted.

**Comment by daikikatsuragawa** [comment]
Or create a `VERSION.txt`.

**Comment by tonyduan** [comment]
I like the `VERSION.txt` approach. If you have the time could you take a stab at that?

**Comment by yutayamazaki** [comment]
@tonyduan @daikikatsuragawa How about this approach used in [optuna](https://github.com/optuna/optuna). I think it's more python friendly way.
- First, create [version.py](https://github.com/optuna/optuna/blob/master/optuna/version.py) that only has a variable `__version__` like `ngboost/__init__.py`.
- Then, read the version number in [setup.py](https://github.com/optuna/optuna/blob/master/setup.py#L13) from `version.py`.

**Comment by daikikatsuragawa** [comment]
@yutayamazaki 
Oh! I think it is good idea!

**Comment by tonyduan** [comment]
Sounds good to me, thank you!
